# Generated by Django 2.0.6 on 2018-06-23 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_auto_20180623_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
