# Generated by Django 2.0.6 on 2018-06-23 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_auto_20180623_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='preco_de_compra',
            field=models.FloatField(default=0.01, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
